services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    networks:
      - hdp-server-network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

networks:
  hdp-server-network:
    driver: bridge

volumes:
  postgres-data-dev:
