version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - local.env
    networks:
      - registery-server-network
    ports:
      - "8080:8080" 
    restart: always

networks:
  registery-server-network:
    driver: bridge

volumes:
  postgres-data-dev: